config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  resources :crime_firs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :user_logins,  controllers: { registrations: 'user_logins/registrations' , sessions: 'user_logins/sessions'}
  resources :messages
  resources :logins
  resources :complaints
  resources :officers
  resources :users
  resources :heads

  devise_scope :user_login do
    root to: 'sessions#new'
  end
  
  post '/submit' => "signups#create"

  get '/viewMyComplaints' => "complaints#mycomplaints"

  get '/viewRequestMsg' => "officers#viewRequestMsg"

  get '/respondMsg/:id' => "messages#respondMsg"

  get '/handledByOfficer/:id' => "complaints#handledByOfficer"

  post '/handledByOfficer/:id' => "complaints#assign_new_officer"

  get '/viewResponse' => "users#viewResponse"

  post  "/remove_officer/:id" => "complaints#remove_officer"

  post "/make_as_lead/:id" => "complaints#make_head"

  get '/complaintHistory/:id' => "complaints#complaint_history"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope :api do
    use_doorkeeper do
        skip_controllers :applications, :authorizations, :authorized_applications
    end
  end

  use_doorkeeper do
    skip_controllers :authorizations, :authorized_applications
  end

  namespace :api ,default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_for :user_logins,  controllers: { registrations: 'user_logins/registrations' , sessions: 'user_logins/sessions'}
    resources :messages
    resources :logins
    resources :complaints
    resources :officers
    resources :users
    resources :heads
    resources :crime_firs

    devise_scope :user_login do
      root to: 'sessions#new'
    end
    
    post '/submit' => "signups#create"

    get '/viewMyComplaints' => "complaints#mycomplaints"

    get '/viewRequestMsg' => "officers#viewRequestMsg"

    get '/respondMsg/:id' => "messages#respondMsg"

    get '/handledByOfficer/:id' => "complaints#handledByOfficer"

    get '/viewResponse' => "users#viewResponse"
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/views/logins/_form.html.erb
<%= form_with(model: login) do |form| %>
  <% if login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
        <% login.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :logouttime %>
    <%= form.datetime_select :logouttime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>Role</th>
      <th>Logouttime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.email %></td>
        <td><%= login.password %></td>
        <td><%= login.role %></td>
        <td><%= login.logouttime %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @login.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.password %>
</p>

<p>
  <strong>Role:</strong>
  <%= @login.role %>
</p>

<p>
  <strong>Logouttime:</strong>
  <%= @login.logouttime %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>