config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  resources :crime_firs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :user_logins,  controllers: { registrations: 'user_logins/registrations' , sessions: 'user_logins/sessions'}
  resources :messages
  resources :logins
  resources :complaints
  resources :officers
  resources :users
  resources :heads

  devise_scope :user_login do
    root to: 'sessions#new'
  end
  
  post '/submit' => "signups#create"

  get '/viewMyComplaints' => "complaints#mycomplaints"

  get '/viewRequestMsg' => "officers#viewRequestMsg"

  get '/respondMsg/:id' => "messages#respondMsg"

  get '/handledByOfficer/:id' => "complaints#handledByOfficer"

  post '/handledByOfficer/:id' => "complaints#assign_new_officer"

  get '/viewResponse' => "users#viewResponse"

  post  "/remove_officer/:id" => "complaints#remove_officer"

  post "/make_as_lead/:id" => "complaints#make_head"

  get '/complaintHistory/:id' => "complaints#complaint_history"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope :api do
    use_doorkeeper do
        skip_controllers :applications, :authorizations, :authorized_applications
    end
  end

  use_doorkeeper do
    skip_controllers :authorizations, :authorized_applications
  end

  namespace :api ,default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_for :user_logins,  controllers: { registrations: 'user_logins/registrations' , sessions: 'user_logins/sessions'}
    resources :messages
    resources :logins
    resources :complaints
    resources :officers
    resources :users
    resources :heads
    resources :crime_firs

    devise_scope :user_login do
      root to: 'sessions#new'
    end
    
    post '/submit' => "signups#create"

    get '/viewMyComplaints' => "complaints#mycomplaints"

    get '/viewRequestMsg' => "officers#viewRequestMsg"

    get '/respondMsg/:id' => "messages#respondMsg"

    get '/handledByOfficer/:id' => "complaints#handledByOfficer"

    get '/viewResponse' => "users#viewResponse"
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/complaint.rb
class Complaint < ApplicationRecord
    belongs_to :user, foreign_key: 'user_id'
    has_many :messages, dependent: :destroy
    has_one :crime_fir, dependent: :destroy
    has_and_belongs_to_many :officers, join_table: :officers_complaints, dependent: :destroy
    has_one :status, through: :crime_fir, dependent: :destroy
    has_one :lead_officer, class_name: 'Officer', foreign_key: 'id', primary_key: 'leadOfficerID', dependent: :destroy

    validates :user_id, presence: true, numericality: { only_integer: true, greater_than: 0 }
    validates :statement, presence: true, length: {minimum: 15}
    validates :location, presence: true, format: { with: /\A[a-zA-Z]+\z/ }
    validates :dateTime, presence: true

    scope :registered, ->{Complaint.joins(:crime_fir).joins(:status).where(statuses:{status: 'Registered'})}
    scope :inprogress, ->{Complaint.joins(:crime_fir).joins(:status).where(statuses:{status: 'Inprogress'})}
    scope :resolved, ->{Complaint.joins(:crime_fir).joins(:status).where(statuses:{status: 'Resolved'})}
    
end 

app/controllers/api/complaints_controller.rb
class Api::ComplaintsController < Api::ApiController 
  before_action :set_complaint, only: %i[ show update destroy handledByOfficer ]

  # GET /complaints
  def index 
    if current_user.present? 
      if current_user.role=='officer' && current_userlogin.present?  && current_userlogin.role=='DSP' 
        @complaints = Complaint.all
      else
        @complaints = current_userlogin.complaints
      end
      if @complaints && @complaints.size>=1
        render json: @complaints, status: 200
      else
        render json: {error: 'No complaints found'}, status: 204
      end
    else
      render json: {error: 'Restricted Access'}, status: 403
    end
  end

  # GET /complaints/1 
  def show
    if current_user.present? && current_userlogin.present?
      @complaints = current_userlogin.complaints
      @complaint = Complaint.find_by(id: params[:id].to_i)
      if @complaint.present?
        if ((@complaints.size>=1 && @complaints.include?(@complaint)) || (current_user.role=='officer' && current_userlogin.role=='DSP'))
          render json: @complaint, status: 200
        else
          render json: {error: 'You are not authorized to view others complaints'}, status: 403
        end
      else
        render json: {error: 'Complaint Not Found'}, status: 404
      end
    else
      render json: {error: 'Restricted Access'}, status: 403
    end
  end

  def mycomplaints
    if current_user.present?
      if current_userlogin.present?
        @complaints = current_userlogin.complaints
        if @complaints && @complaints.size >= 1
            render json: @complaints, status: 200
        else
          render json: {notice: 'You have not made any complaints'}, status: 204
        end
      else
        render json: {error: 'User Not Found'}, status: 404
      end
    else
      render json: {error: 'Restricted Access'}, status: 403
    end
  end

  def handledByOfficer
    if current_user.present? && current_userlogin.present?
      @complaints = current_userlogin.complaints
      @complaint = Complaint.find_by(id: params[:id].to_i)
      if @complaint.present? 
        if ((current_user.role=='officer' && current_userlogin.role=='DSP') || (@complaints.size>=1 && @complaints.include?(@complaint)))
          @officers = @complaint.officers 
          if @officers && @officers.size>=1
            render json: @officers, status: 200
          else
            render json: {error: 'This complaint is not yet assigned to any officer'}, status: 204
          end
        else
          render json: {error: 'You are not authorized to view others complaints'}, status: 403
        end
      else
        render json: {error: 'Complaint Not Found'}, status: 404
      end
    else
      render json: {error: 'Restricted Access'}, status: 403
    end
  end

  # POST /complaints 
  def create
    if current_user.present? 
      @complaint = Complaint.new(complaint_params)
      if current_user.role=='user'
        @complaint.user_id = current_userlogin.id
        @officer = Officer.find_by(role: 'DSP')
        if @complaint.save &&  current_userlogin && current_userlogin.update(noOfComplaintsMade: current_userlogin.noOfComplaintsMade + 1 )
          @officers_complaints = OfficersComplaint.new(officer_id: @officer.id, complaint_id: @complaint.id, IsHead: "Yes")
          if @officers_complaints.save
            render json: @complaint, status: 200
          else
            render json: {error: @officers_complaints.errors.full_messages}, status: 204
          end
        else
          render json: {error: @complaint.errors.full_messages}, status: 204
        end
      else
        @officer = Officer.find_by(role: 'DSP')
        @user = User.find_by(id: params[:complaint][:user_id])
        if @user && @user.update(noOfComplaintsMade: @user.noOfComplaintsMade + 1 ) && @complaint.save 
          @officers_complaints = OfficersComplaint.new(officer_id: @officer.id, complaint_id: @complaint.id, IsHead: "Yes")
          if @officers_complaints.save
            render json: @complaint, status: 200
          else
            render json: {error: @officers_complaints.errors.full_messages}, status: 204
          end
        else
          render json: {error: 'User Not Found'}, status: 404
        end
      end
    else
      render json: {error: 'Restricted Access'}, status: 403
    end
  end

  # PATCH/PUT /complaints/1 
  def update
    if current_user.present? && current_userlogin.present?
      @complaints = current_userlogin.complaints
      @complaint = Complaint.find_by(id: params[:id].to_i)
      if @complaint.present? 
        if ((current_user.role=='officer' && current_userlogin.role=='DSP') || (@complaints.size>=1 && @complaints.include?(@complaint)))
          if params[:complaint][:user_id]!=nil 
            render json: {error: 'ID cannot be updated'}, status: 403
          else
            if params[:complaint][:statement]!=nil 
              @complaint.statement = params[:complaint][:statement]
            end
            if params[:complaint][:location]!=nil 
              @complaint.location =params[:complaint][:location]
            end
            if params[:complaint][:dateTime]!=nil 
              @complaint.dateTime = params[:complaint][:dateTime]
            end
            if @complaint.save
              render json: @complaint, status: 200
            else
              render json: {error: @complaint.errors.full_messages}, status: 204
            end
          end
        else
          render json: {error: 'You are not authorized to edit others complaints'}, status: 403
        end
      else
        render json: {error: 'Complaint Not Found'}, status: 404
      end
    else
      render json: {error: 'Restricted Access'}, status: 403
    end
  end

  # DELETE /complaints/1 
  def destroy
    if current_user.present? && current_userlogin.present?
      @complaints = current_userlogin.complaints
      @complaint = Complaint.find_by(id: params[:id].to_i)
      if @complaint.present? 
        if ((current_user.role=='officer' && current_userlogin.role=='DSP') || (@complaints.size>=1 && @complaints.include?(@complaint)))
          if @complaint.destroy
            render json: { message: "Complaint deleted successfully" } , status: 200
          else
            render json: {error: @complaint.errors.full_messages} , status: 204
          end
        else
          render json: {error: 'You are not authorized to delete others complaints'}, status: 403
        end
      else
        render json: {error: 'Complaint does not exist'}, status: 404
      end
    else
      render json: {error: 'Unauthorized Access'}, status: 401
    end
  end

  private

    def set_complaint
      @complaint = Complaint.find_by(id: params[:id])
      unless @complaint 
        render json: {error: 'Complaint does not exist'}, status: 404
      end
    end

    # Only allow a list of trusted parameters through.
    def complaint_params
      params.require(:complaint).permit(:user_id, :statement, :location, :dateTime)
    end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: %i[ show edit update destroy handledByOfficer ]
  before_action :authenticate_user_login!
  before_action :check_for_messages

  # GET /complaints
  def index
    if current_user_login.role=='officer' && Current.user.role=='DSP'
      sort_order = %w(Registered Inprogress Resolved)
      @complaints = Complaint.all.sort_by{ |complaint| sort_order.index(complaint.status ? complaint.status.status : 'Registered') }
    elsif current_user_login.role=='officer'
      sort_order = %w(Registered Inprogress Resolved)
      @complaints = Current.user.complaints.sort_by{ |complaint| sort_order.index(complaint.status ? complaint.status.status : 'Registered') }
    elsif current_user_login.role=='user'
      redirect_user("Unauthorized Access")
    end
  end

  # GET /complaints/1 
  def show
    @complaint = Complaint.find_by(id: params[:id])
    @complaints = Current.user.complaints
    unless @complaints && @complaints.include?(@complaint) || (current_user_login.role=='officer' && Current.user.role=='DSP')
      redirect_user("Unauthorized Access")
    end
  end

  def mycomplaints
    if current_user_login.role=='user'
      sort_order = %w(Registered Inprogress Resolved)
      @user = User.find_by(id: Current.user.id)
      @complaints = @user.complaints.sort_by{ |complaint| sort_order.index(complaint.status ? complaint.status.status : 'Registered') }
    else
      redirect_user("Unauthorized Access")
    end
  end

  def assign_new_officer
    @officers_complaints = OfficersComplaint.new(officer_id: params[:assign_to_officer], complaint_id: params[:id], IsHead: "No")
    if @officers_complaints.save
      flash[:notice] = 'Officer Assigned Successfully'
      redirect_to "/handledByOfficer/#{params[:id]}"
    else
      flash[:alert] = 'Some unknown error occured'
      redirect_to "/handledByOfficer/#{params[:id]}"
    end
  end

  def remove_officer
    @complaint = OfficersComplaint.find_by(officer_id: params[:officer_id], complaint_id: params[:complaint_id])
    if @complaint && @complaint.IsHead == 'Yes'
      flash[:alert] = 'Lead Officer cannot be removed. please assign some other officer as lead and then try!!'
      redirect_to "/handledByOfficer/#{params[:complaint_id]}"
    elsif @complaint.destroy
      flash[:notice] = 'Officer Removed Successfully'
      redirect_to "/handledByOfficer/#{params[:complaint_id]}"
    else
      flash[:alert] = @complaint.error.full_messages
      redirect_to "/handledByOfficer/#{params[:complaint_id]}"
    end 
  end

  def complaint_history
    @complaint = Complaint.find_by(id: params[:id])
    @officers = @complaint.officers
    @messages = @complaint.messages.where(message_type: 'User')
  end

  def make_head
    @officer1 = OfficersComplaint.find_by(complaint_id: params[:complaint_id], IsHead:'Yes')
    @officer2 = OfficersComplaint.find_by(officer_id: params[:officer_id], complaint_id: params[:complaint_id])

    if @officer1.update(IsHead: 'No') && @officer2.update(IsHead: 'Yes')
      flash[:notice] = 'Lead Changed Successfully'
      redirect_to "/handledByOfficer/#{params[:complaint_id]}"
    else
      flash[:alert] = @officer2.error.full_messages
      redirect_to "/handledByOfficer/#{params[:complaint_id]}"
    end 
  end

  def handledByOfficer
    @complaint = Complaint.find_by(id: params[:id])
    @complaints = Current.user.complaints
    if @complaint
      unless ((@complaints && @complaints.include?(@complaint)) || (@current_user_login.role=='officer' && Current.user.role=='DSP'))
        redirect_user("Unauthorized Access")
      else
        @officers = @complaint.officers.order(:created_at)
      end
    else
      redirect_user("Invalid ID")
    end
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
    @complaint = Complaint.find_by(id: params[:id])
    @complaints = Current.user.complaints
    unless ((@complaints && @complaints.include?(@complaint)) || (@current_user_login.role=='officer' && Current.user.role=='DSP'))
      redirect_user("Unauthorized Access")
    end
  end
 
  # POST /complaints 
  def create
    @complaint = Complaint.new(complaint_params)
    @officer = Officer.find_by(role: 'DSP')
    @user = User.find_by(id: params[:complaint][:user_id])  
    @user.update(noOfComplaintsMade: @user.noOfComplaintsMade+1)
    respond_to do |format|
      if @complaint.save 
        @officers_complaints = OfficersComplaint.new(officer_id: @officer.id, complaint_id: @complaint.id, IsHead: "Yes")
        if @officers_complaints.save
          format.html { redirect_to complaint_url(@complaint), notice: "Complaint was successfully created." }
          format.json { render :show, status: :created, location: @complaint }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @complaint.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1 
  def update
    @complaint = Complaint.find_by(id: params[:id])
    @complaints = Current.user.complaints
    if @complaints && @complaints.include?(@complaint) || (current_user_login.role=='officer' && Current.user.role=='DSP')
      respond_to do |format|
        if @complaint.update(complaint_params)
          format.html { redirect_to complaint_url(@complaint), notice: "Complaint was successfully updated." }
          format.json { render :show, status: :ok, location: @complaint }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @complaint.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_user("Unauthorized Access")
    end
  end

  # DELETE /complaints/1 
  def destroy
    @complaint.destroy

    respond_to do |format|
      format.html { redirect_to complaints_url, notice: "Complaint was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find_by(id: params[:id])
      unless @complaint 
        redirect_user("Invalid Complaint ID")
      end
    end

    # Only allow a list of trusted parameters through.
    def complaint_params
      params.require(:complaint).permit(:user_id, :statement, :location, :dateTime)
    end


end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_with(model: complaint) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
        <% complaint.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user_login.role=="user"%>
    <div class="form-group p-2">
      <input class="form-control shadow shadow-sm"  type="hidden" name="complaint[user_id]" value=<%= complaint.user_id==nil ? Current.user.id : complaint.user_id%> readonly>
    </div>
  <% else %>
    <div class="form-group p-2">
      <label class= "form-label fw-bold fs-5 py-2" for="user_id">User</label>
      <%= form.select :user_id, options_for_select(User.all.map { |c| [c.name, c.id] }, complaint.user ? complaint.user.id : nil), { include_blank: 'Select'}, {class: "form-select shadow shadow-sm ", required: true}  %>
    </div>
  <% end %>

  <div class="form-group p-2">
    <label class= "form-label fw-bold fs-5 py-2" for="statement">Statement</label>
    <input class="form-control shadow shadow-sm"  type="text" name="complaint[statement]" value="<%= complaint.statement %>" >
  </div>

  <div class="form-group p-2">
    <label class= "form-label fw-bold fs-5 py-2" for="location">Location</label>
    <input class="form-control shadow shadow-sm"  type="text" name="complaint[location]" value="<%= complaint.location %>" >
  </div>
  
  <div class="form-group p-2">
    <label class= "form-label fw-bold fs-5 py-2" for="dateTime">Date & Time</label>
    <input class="form-control shadow shadow-sm"  type="datetime-local" name="complaint[dateTime]" value=<% if complaint.dateTime %><%= complaint.dateTime.strftime('%Y-%m-%dT%H:%M') %><% end %> >
  </div>

  <div class="actions form-group d-flex justify-content-center py-4">
    <%= form.submit "Submit", class: "btn btn-secondary shadow shadow-sm mx-2"%>
     <% if current_user_login.role=='officer' %>
      <%= link_to 'Back', complaints_path, class: "btn btn-secondary text-light btn-lg mx-2"%>
    <% else %>
      <%= link_to 'Back', viewMyComplaints_path , class: "btn btn-secondary text-light btn-lg mx-2"%>
    <% end %>
  </div>
<% end %>

app/views/complaints/edit.html.erb
<div class="mt-5">
    <h1 class="d-flex flex-row fw-bold justify-content-center pt-4">Edit Complaint Details</h1>
    <div class="border border-sm rounded m-5 p-5">
        <div class="d-flex flex-column justify-content-center px-5 mx-5">
            <%= render 'form', complaint: @complaint %>
        </div>
    <div>
</div>

app/views/complaints/index.html.erb
<div class="mt-5">
  <h1 class="d-flex flex-row fw-bold justify-content-center pt-4">Complaints</h1>
  <div class="border border-sm rounded m-5 p-5">
    <div class="px-5 mx-5">
      <table class="table table-responsive table-striped">
        <thead class="thead-dark bg-dark text-light align-text-center">
          <tr>
            <th class="p-4 fs-5">User</th>
            <th class="p-4 fs-5">Statement</th>
            <th class="p-4 fs-5">Location</th>
            <th class="p-4 fs-5">Status</th>
            <% if current_user_login.role=='officer' %>
               <th class="p-4 fs-5">FIR</th>
            <% end %>
            <th class="p-4 fs-5">Datetime</th>
            <th colspan="4"></th>
          </tr>
        </thead>

        <tbody>
          <% @complaints.each do |complaint| %>
            <tr>
              <td class="p-4 fs-6"><%= complaint.user.name %></td>
              <td class="p-4 fs-6"><%= complaint.statement %></td>
              <td class="p-4 fs-6"><%= complaint.location %></td>
              <td class="p-4 fs-6"><% if complaint.status %><%= complaint.status.status %><% else %><%= "Registered" %><% end %></td>
              <% if current_user_login.role=='officer' %>
                <% if complaint.crime_fir %>
                  <td class="p-4 fs-6"><%= link_to 'View', complaint.crime_fir %></td>
                <% else %>
                  <td class="p-4 fs-6"><%= link_to 'Create', new_crime_fir_path(complaint_id: complaint.id, user_id: complaint.user_id) %>
                <% end %>
              <% end %> 
              <td class="p-4 fs-6"><%= complaint.dateTime.strftime('%B %d - %Y, %I:%M %p')  %></td>
              <% if (complaint.status && complaint.status.status == 'Resolved')%>
                <td class="p-4 fs-6"><%= link_to "/complaintHistory/#{complaint.id}" do %>
                      <i class="icon fa-solid fa-clock-rotate-left fa-xl" data-toggle="tooltip" data-placement="top" title="View History"></i>
                    <% end %>
                </td>  
                <td></td>
                <td></td>
                <td></td>
              <% else %>
                <td class="p-4"><a href="handledByOfficer/<%= complaint.id %>"><i class="icon fa-solid fa-user-nurse fa-2xl" data-toggle="tooltip" data-placement="top" title="Governed By"></i></a></td>
                <% if current_user_login.role=='user'%>
                  <td class="p-4"><%= link_to new_message_path(complaint_id: complaint.id) do %>
                        <i class="icon fa-solid fa-paper-plane fa-2xl" data-toggle="tooltip" data-placement="top" title="Make Request"></i>
                      <% end %>
                  </td>
                <% end %>
                <td class="p-4 fs-6"><%= link_to edit_complaint_path(complaint) do %>
                      <i class="icon fa-solid fa-pen-to-square fa-xl" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                    <% end %>
                </td>
                <td class="p-4 fs-6"><%= link_to "/complaintHistory/#{complaint.id}" do %>
                  <i class="icon fa-solid fa-clock-rotate-left fa-xl" data-toggle="tooltip" data-placement="top" title="View History"></i>
                  <% end %>
                </td>  
              <% end %>       
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Complaint', new_complaint_path , class: "btn btn-secondary text-light btn-lg"%>
    </div>
  <div>
</div>

app/views/complaints/mycomplaints.html.erb
<div class="mt-5">
  <h1 class="d-flex flex-row fw-bold justify-content-center pt-4">Complaints</h1>
  <div class="border border-sm rounded m-5 p-5">
    <div class="px-5 mx-5">
      <table class="table table-responsive table-striped">
        <thead class="thead-dark bg-dark text-light align-text-center">
          <tr>
            <th class="p-4 fs-5">User</th>
            <th class="p-4 fs-5">Statement</th>
            <th class="p-4 fs-5">Location</th>
            <th class="p-4 fs-5">Status</th>
            <th class="p-4 fs-5">Datetime</th>
            <th colspan="4"></th>
          </tr>
        </thead>

        <tbody>
          <% @complaints.each do |complaint| %>
            <tr>
              <td class="p-4 fs-6"><%= complaint.user.name %></td>
              <td class="p-4 fs-6"><%= complaint.statement %></td>
              <td class="p-4 fs-6"><%= complaint.location %></td>
              <td class="p-4 fs-6"><% if complaint.status %><%= complaint.status.status %><% else %><%= "Registered" %><% end %></td>
              <td class="p-4 fs-6"><%= complaint.dateTime.strftime('%B %d - %Y, %I:%M %p')  %></td>
              <% if (complaint.status && complaint.status.status == 'Resolved')%>
                <td class="p-4 fs-6"><%= link_to "/complaintHistory/#{complaint.id}" do %>
                      <i class="icon fa-solid fa-clock-rotate-left fa-xl" data-toggle="tooltip" data-placement="top" title="View History"></i>
                    <% end %>
                </td>  
                <td></td>
                <td></td>
                <td></td>
              <% else %>
                <td class="p-4"><a href="handledByOfficer/<%= complaint.id %>"><i class="icon fa-solid fa-user-nurse fa-2xl" data-toggle="tooltip" data-placement="top" title="Governed By"></i></a></td>
                <% if current_user_login.role=='user'%>
                  <td class="p-4"><%= link_to new_message_path(complaint_id: complaint.id) do %>
                        <i class="icon fa-solid fa-paper-plane fa-2xl" data-toggle="tooltip" data-placement="top" title="Make Request"></i>
                      <% end %>
                  </td>
                <% end %>
                <td class="p-4 fs-6"><%= link_to edit_complaint_path(complaint) do %>
                      <i class="icon fa-solid fa-pen-to-square fa-xl" data-toggle="tooltip" data-placement="top" title="Edit"></i>
                    <% end %>
                </td>
                <td class="p-4 fs-6"><%= link_to "/complaintHistory/#{complaint.id}" do %>
                  <i class="icon fa-solid fa-clock-rotate-left fa-xl" data-toggle="tooltip" data-placement="top" title="View History"></i>
                  <% end %>
                </td>  
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Complaint', new_complaint_path , class: "btn btn-secondary text-light btn-lg"%>
    </div>
  <div>
</div>

app/views/complaints/new.html.erb
<div class="mt-5">
    <h1 class="d-flex flex-row fw-bold justify-content-center pt-4">Add New Complaint</h1>
    <div class="border border-sm rounded m-5 p-5">
        <div class="d-flex flex-column justify-content-center px-5 mx-5">
            <%= render 'form', complaint: @complaint %>
        </div>
    <div>
</div>

app/views/complaints/show.html.erb
<div class="mt-5">
  <h1 class="d-flex flex-row fw-bold justify-content-center pt-4">Complaints</h1>
  <div class="border border-sm rounded m-5 p-5">
    <div class="px-5 mx-5">
      <table class="table table-responsive">
        <tr>
          <td class="p-4 fs-4 fw-bold">User:</td>
          <td class="p-4 fs-4"><%=  @complaint.user.name %></td>
        </tr>
        
        <tr>
          <td class="p-4 fs-4 fw-bold">Statement:</td>
          <td class="p-4 fs-4"><%= @complaint.statement %></td>
        </tr>

        <tr>
          <td class="p-4 fs-4 fw-bold">Location:</td>
          <td class="p-4 fs-4"><%= @complaint.location %></td>
        </tr>
        
       <tr>
          <td class="p-4 fs-4 fw-bold">Status:</td>
          <td class="p-4 fs-4"><% if @complaint.status %><%= @complaint.status.status %><% else %><%= "Registered" %><% end %></td>
        </tr>

        <tr>
          <td class="p-4 fs-4 fw-bold">Datetime:</td>
          <td class="p-4 fs-4"><%= @complaint.dateTime.strftime('%B %d - %Y, %I:%M %p') %></td>
        </tr>
      </table>
    </div>
  <div>
</div>