config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  resources :crime_firs
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :user_logins,  controllers: { registrations: 'user_logins/registrations' , sessions: 'user_logins/sessions'}
  resources :messages
  resources :logins
  resources :complaints
  resources :officers
  resources :users
  resources :heads

  devise_scope :user_login do
    root to: 'sessions#new'
  end
  
  post '/submit' => "signups#create"

  get '/viewMyComplaints' => "complaints#mycomplaints"

  get '/viewRequestMsg' => "officers#viewRequestMsg"

  get '/respondMsg/:id' => "messages#respondMsg"

  get '/handledByOfficer/:id' => "complaints#handledByOfficer"

  post '/handledByOfficer/:id' => "complaints#assign_new_officer"

  get '/viewResponse' => "users#viewResponse"

  post  "/remove_officer/:id" => "complaints#remove_officer"

  post "/make_as_lead/:id" => "complaints#make_head"

  get '/complaintHistory/:id' => "complaints#complaint_history"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope :api do
    use_doorkeeper do
        skip_controllers :applications, :authorizations, :authorized_applications
    end
  end

  use_doorkeeper do
    skip_controllers :authorizations, :authorized_applications
  end

  namespace :api ,default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    devise_for :user_logins,  controllers: { registrations: 'user_logins/registrations' , sessions: 'user_logins/sessions'}
    resources :messages
    resources :logins
    resources :complaints
    resources :officers
    resources :users
    resources :heads
    resources :crime_firs

    devise_scope :user_login do
      root to: 'sessions#new'
    end
    
    post '/submit' => "signups#create"

    get '/viewMyComplaints' => "complaints#mycomplaints"

    get '/viewRequestMsg' => "officers#viewRequestMsg"

    get '/respondMsg/:id' => "messages#respondMsg"

    get '/handledByOfficer/:id' => "complaints#handledByOfficer"

    get '/viewResponse' => "users#viewResponse"
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-sm navbar-custom position-sticky top-0" style="background-color: #94e5ff; height: 70px; z-index: 100;">
    <div class="container-fluid mx-5">
      <a class="navbar-brand" href="#">Crime Record Management System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ms-auto"> 
          <li class="nav-item">
            <% if current_user_login.role=="user"%>
            <a class="nav-link fs-5 px-3 <%= 'active' if current_page?(user_path(Current.user.id)) %>" href="<%= user_path(Current.user.id)%>">Profile</a>
            <% elsif current_user_login.role=="officer"%>
            <a class="nav-link fs-5 px-3 <%= 'active' if current_page?(officer_path(Current.user.id)) %>" href="<%= officer_path(Current.user.id)%>">Profile</a>
            <% elsif current_user_login.role=="admin"%>
            <a class="nav-link fs-5 px-3 <%= 'active' if current_page?(head_path(Current.user.id)) %>" href="<%= head_path(Current.user.id)%>">Profile</a>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_login_session_path, method: :delete, data: { confirm: 'Do you want to signout' } , class: 'nav-link fs-5 px-3' %>
          </li>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_sidenavbar.html.erb
<nav class="navbar navbar-expand-md navbar-side sticky-top" style="z-index: 90;">
    <div class="text-center p-3">
        <img src="<%= image_path('profile.png') %>" alt="user profile image" class="img-fluid rounded-circle mb-5 mt-2 p-1 d-none d-md-block shadow">
        <a href="#" class="navbar-brand mx-0 font-weight-bold text-nowrap"><%= Current.user.name %></a>
    </div>
    <ul class="navbar-nav flex-column w-100 justify-content-center">
        <% if(current_user_login.role =="user") %>
            <li class="nav-item p-3">
                <a href="<%= new_complaint_path %>" class="nav-link fs-4  <%= 'active' if current_page?(new_complaint_path) %>">Add Complaint</a>
            </li>
            <li class="nav-item p-3">
                <a href="<%= viewMyComplaints_path  %>" class="nav-link fs-4  <%= 'active' if current_page?(viewMyComplaints_path)%>">View Complaints</a>
            </li>
            <li class="nav-item p-3">
                <a href="<%= viewResponse_path %>" class="nav-link fs-4 <%= 'active' if current_page?(viewResponse_path)%>">View Response</a>
            </li>
        <% elsif(current_user_login.role =="officer") %>
            <% if(Current.user.role=="DSP") %>
                <li class="nav-item p-3">
                    <a href="<%= officers_path %>" class="nav-link fs-4 <%= 'active' if current_page?( officers_path )%>">Officers</a>
                </li>
            <% end %>
            <li class="nav-item p-3">
                <a href="<%= complaints_path  %>" class="nav-link fs-4 <%= 'active' if current_page?(complaints_path)%>">Complaints</a>
            </li>
            <li class="nav-item p-3">
                <a href="<%= users_path %>" class="nav-link fs-4 <%= 'active' if current_page?(users_path)%>">Users</a>
            </li>
            <li class="nav-item p-3">
                <a href="<%= viewRequestMsg_path %>" class="nav-link fs-4 <%= 'active' if current_page?(viewRequestMsg_path)%>">Request Messages</a>
            </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectPostgress</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js" integrity="sha512-fD9DI5bZwQxOi7MhYWnnNPlvXdp/2Pj3XSTRrFs5FQa4mizyGLnJcN6tuvUS6LbmgN1ut+XGSABKvjN0H6Aoow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_login_signed_in? %>
      <div class="container-fluid body">
        <div class="row">
          <%= render 'layouts/navbar'%>
        <div class="row">
          <%= render 'layouts/sidenavbar'%>          
          <div class="col">
            <div class="content-wrapper">
                <%= yield %>
                <%= toastr_flash %>
            </div>
          </div>
        </div>
        </div>
      </div>
    <% else %>
    <div class="container-fluid ses-body">
      <div class="body-wrapper">
        <div class="in-content px-5 py-3">
          <%= yield %>
          <%= toastr_flash %>
        </div>
      </div>
    </div>
    <% end %>
  </body>
</html>